### ISSUE TITLE
Error running cake dev

### ISSUE THREAD

**Issue by m3talsmith** [RickCarlino/simple_audio#2]
If I run `cake dev` I get the following error:

``` zsh
% cake dev

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:980:11)
  at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Any ideas?

**Comment by RickCarlino** [comment]
I didn't make a package.json. If I did, it would include:
- static-here
- child_process
- coffee-script

**Comment by RickCarlino** [comment]
This error has been fixed by pull request 3, which updates the build process.
