### ISSUE TITLE
Get Permission Fails

### ISSUE THREAD

**Issue by 7yl4r** [RickCarlino/simple_audio#5]
Get Permissions link appears to do nothing. Console shows following error:

```
Uncaught TypeError: 
Failed to execute 'webkitGetUserMedia' on 'Navigator': 
The callback provided as parameter 3 is not a function.
Recording 
@ recorder.js:12(anonymous function) 
@ demo.js:6x.event.dispatch 
@ jquery.min.js:5x.event.add.y.handle 
@ jquery.min.js:5
```

chrome v 44.0.2403.130 m
windows 7 pro (Version  6.1.7601 Service Pack 1 Build 7601)

**Comment by RickCarlino** [comment]
I'm pretty sure that the browser APIs have changed since the time that I wrote this.

At this point, I don't have time to maintain the project. I will update the repo description accordingly. Sorry for any inconvenience.

**Comment by 7yl4r** [comment]
No problem, I wasn't looking in detail. I just saw the error and figured it
might help to report it.

**Comment by RickCarlino** [comment]
Really appreciate it! Thanks for the help and sorry I couldn't be of more assitance.
